// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jopfdnbbhfhcgfxlpulf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvcGZkbmJiaGZoY2dmeGxwdWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjE3MTQsImV4cCI6MjA3MDk5NzcxNH0.kqk0C2lfq5qTA9ehNeyww6KmuKpA9rRE_at7bf5kzuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});